/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package login.screen;
import java.awt.Component;
import java.lang.Object;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.time.LocalDate;
import java.util.Calendar;
/**
 *
 * @author xpeng
 */
public class PanelDate extends javax.swing.JLayeredPane {
    private int month;
    private int year,grade;
    private String name,surname,set;
    DBConnection db = new DBConnection();
    /**
     * Creates new form MainScreen
     */
    public PanelDate(int month,int year,String name,String surname, int grade,String set){
        initComponents();
        this.month=month;this.year=year;
        this.name=name;this.surname=surname;this.grade=grade;this.set=set;
        init();
        
    }
    private void init(){
        mon.asTitle();
        tue.asTitle();
        wed.asTitle();
        thu.asTitle();
        fri.asTitle();
        sat.asTitle();
        sun.asTitle();
        setDate();
    }
    private void setDate() {
        Calendar calendar = Calendar.getInstance();
        calendar.set(Calendar.YEAR, year);
        calendar.set(Calendar.MONTH, month - 1);  //  month jan as 0 so start from 0
        calendar.set(Calendar.DATE, 1);
        int startDay = calendar.get(Calendar.DAY_OF_WEEK) - 1;  //  get day of week -1 to index
        calendar.add(Calendar.DATE, -startDay);
        //ToDay toDay = getToDay();
//        Login account = new Login();
//        String[] fullname=account.getUsername();
//        String name = fullname[0];
        //String surname = fullname[1];
        //int grade = account.getGrade();
        //String set=""+db.getResults("SELECT TOP MathSet WHERE Name="+name+" AND Grade="+grade);
        for (Component com : getComponents()) {
            Cell cell = (Cell) com;
            if (!cell.isTitle()) {
                cell.setText(calendar.get(Calendar.DATE)+"");
                cell.setDate(calendar.getTime());
                cell.currentMonth(calendar.get(Calendar.MONTH) == month - 1);
                calendar.add(Calendar.DATE, 1); //  up 1 day
                //System.out.println(cell.date.toLocaleString());
                //System.out.println(cell.date.toGMTString());
                String year = ""+cell.date.getYear();
                year="20"+year.charAt(1)+year.charAt(2);
                //System.out.println(cell.date);
                //System.out.println( cell.date.getDate());
               try {
                    LocalDate l = LocalDate.of(cell.date.getYear(), cell.date.getMonth(), cell.date.getDate());
                    ResultSet rs = db.getDescription(this.name, surname, set, grade, l);
                    String description = "";
                    if (rs != null) {
                        description = rs.toString();
                    }
                    cell.setText(calendar.get(Calendar.DATE) + "\n" + description);
                } catch (java.time.DateTimeException ex) {

                }
                
                
                //String description=""+db.getResults("SELECT Description FROM Subjects WHERE Grade="+grade+
               //         " AND Name"+name+"AND MathSet="+set);         
               // cell.setText(calendar.get(Calendar.DATE)+"\n"+description);
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        sun = new login.screen.Cell();
        mon = new login.screen.Cell();
        tue = new login.screen.Cell();
        wed = new login.screen.Cell();
        thu = new login.screen.Cell();
        fri = new login.screen.Cell();
        sat = new login.screen.Cell();
        cell8 = new login.screen.Cell();
        cell9 = new login.screen.Cell();
        cell10 = new login.screen.Cell();
        cell11 = new login.screen.Cell();
        cell12 = new login.screen.Cell();
        cell13 = new login.screen.Cell();
        cell14 = new login.screen.Cell();
        cell15 = new login.screen.Cell();
        cell16 = new login.screen.Cell();
        cell17 = new login.screen.Cell();
        cell18 = new login.screen.Cell();
        cell19 = new login.screen.Cell();
        cell20 = new login.screen.Cell();
        cell21 = new login.screen.Cell();
        cell22 = new login.screen.Cell();
        cell23 = new login.screen.Cell();
        cell24 = new login.screen.Cell();
        cell25 = new login.screen.Cell();
        cell26 = new login.screen.Cell();
        cell27 = new login.screen.Cell();
        cell28 = new login.screen.Cell();
        cell29 = new login.screen.Cell();
        cell30 = new login.screen.Cell();
        cell31 = new login.screen.Cell();
        cell32 = new login.screen.Cell();
        cell33 = new login.screen.Cell();
        cell34 = new login.screen.Cell();
        cell35 = new login.screen.Cell();
        cell36 = new login.screen.Cell();
        cell37 = new login.screen.Cell();
        cell38 = new login.screen.Cell();
        cell39 = new login.screen.Cell();
        cell40 = new login.screen.Cell();
        cell41 = new login.screen.Cell();
        cell42 = new login.screen.Cell();
        cell43 = new login.screen.Cell();
        cell44 = new login.screen.Cell();
        cell45 = new login.screen.Cell();
        cell46 = new login.screen.Cell();
        cell47 = new login.screen.Cell();
        cell48 = new login.screen.Cell();
        cell49 = new login.screen.Cell();

        setLayout(new java.awt.GridLayout(7, 7));

        sun.setText("Sun");
        sun.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sunActionPerformed(evt);
            }
        });
        add(sun);

        mon.setText("Mon");
        add(mon);

        tue.setText("Tue");
        add(tue);

        wed.setText("Wed");
        add(wed);

        thu.setText("Thu");
        add(thu);

        fri.setText("Fri");
        add(fri);

        sat.setText("Sat");
        add(sat);
        add(cell8);
        add(cell9);
        add(cell10);
        add(cell11);
        add(cell12);
        add(cell13);
        add(cell14);
        add(cell15);
        add(cell16);
        add(cell17);
        add(cell18);
        add(cell19);
        add(cell20);
        add(cell21);
        add(cell22);
        add(cell23);
        add(cell24);
        add(cell25);
        add(cell26);
        add(cell27);
        add(cell28);
        add(cell29);
        add(cell30);
        add(cell31);
        add(cell32);
        add(cell33);
        add(cell34);
        add(cell35);
        add(cell36);
        add(cell37);
        add(cell38);
        add(cell39);
        add(cell40);
        add(cell41);
        add(cell42);
        add(cell43);
        add(cell44);
        add(cell45);
        add(cell46);
        add(cell47);

        cell48.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cell48ActionPerformed(evt);
            }
        });
        add(cell48);
        add(cell49);
    }// </editor-fold>//GEN-END:initComponents

    private void sunActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sunActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sunActionPerformed

    private void cell48ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cell48ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cell48ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private login.screen.Cell cell10;
    private login.screen.Cell cell11;
    private login.screen.Cell cell12;
    private login.screen.Cell cell13;
    private login.screen.Cell cell14;
    private login.screen.Cell cell15;
    private login.screen.Cell cell16;
    private login.screen.Cell cell17;
    private login.screen.Cell cell18;
    private login.screen.Cell cell19;
    private login.screen.Cell cell20;
    private login.screen.Cell cell21;
    private login.screen.Cell cell22;
    private login.screen.Cell cell23;
    private login.screen.Cell cell24;
    private login.screen.Cell cell25;
    private login.screen.Cell cell26;
    private login.screen.Cell cell27;
    private login.screen.Cell cell28;
    private login.screen.Cell cell29;
    private login.screen.Cell cell30;
    private login.screen.Cell cell31;
    private login.screen.Cell cell32;
    private login.screen.Cell cell33;
    private login.screen.Cell cell34;
    private login.screen.Cell cell35;
    private login.screen.Cell cell36;
    private login.screen.Cell cell37;
    private login.screen.Cell cell38;
    private login.screen.Cell cell39;
    private login.screen.Cell cell40;
    private login.screen.Cell cell41;
    private login.screen.Cell cell42;
    private login.screen.Cell cell43;
    private login.screen.Cell cell44;
    private login.screen.Cell cell45;
    private login.screen.Cell cell46;
    private login.screen.Cell cell47;
    private login.screen.Cell cell48;
    private login.screen.Cell cell49;
    private login.screen.Cell cell8;
    private login.screen.Cell cell9;
    private login.screen.Cell fri;
    private login.screen.Cell mon;
    private login.screen.Cell sat;
    private login.screen.Cell sun;
    private login.screen.Cell thu;
    private login.screen.Cell tue;
    private login.screen.Cell wed;
    // End of variables declaration//GEN-END:variables
}
